export * as Body from "@vue-email/body";
export * as Button from "@vue-email/button";
// export * as Code from "@vue-email/code-block";
// export * from "@vue-email/code-inline";
export * as Column from "@vue-email/column";
export * as Container from "@vue-email/container";
export * as Font from "@vue-email/font";
export * as Head from "@vue-email/head";
export * as Heading from "@vue-email/heading";
export * as Hr from "@vue-email/hr";
export * as Html from "@vue-email/html";
export * as Img from "@vue-email/img";
export * as Link from "@vue-email/link";
export * as Markdown from "@vue-email/markdown"; 
export * as Preview from "@vue-email/preview";
export * as Row from "@vue-email/row";
export * as Section from "@vue-email/section";
export * as Tailwind from "@vue-email/tailwind";
export * as Text from "@vue-email/text";
export * from "@vue-email/render";
