export const patterns = {
  h1: /^#\s+(.+)$/gm,
  h2: /^##\s+(.+)$/gm,
  h3: /^###\s+(.+)$/gm,
  h4: /^####\s+(.+)$/gm,
  h5: /^#####\s+(.+)$/gm,
  h6: /^######\s+(.+)$/gm,
  p: /((\n|^)(?!\n)((?!<\/?(h|ul|ol|pre|div|blockquote)[>\s]).)+(\n|$)+)+/gm,
  bold: /\*\*(.+?)\*\*/g,
  italic: /\*(.+?)\*/g,
  li: /^\s*[-|]\s+(.*)$/gm,
  ul: /(<li.*<\/li>)(?![\s\S]*<\/ul>)/gs,
  image: /!\[(.*?)\]\((.*?)\)/g,
  link: /\[(.+?)\]\((.*?)\)/g,
  codeBlocks: /```(.+?)```/gs,
  codeInline: /`(.+?)`/g,
  br: / {2}\n/g,
  hr: /^-{3,}$/gm,
  table:
    /((?:^|\n)(?:\|[^\n]*?)+\|\n)((?:^|\n)(?:\|(?:[\s\S]*?[^\\])?\|[^\n]*)+\|\n)+/gm,
  strikethrough: /~~(.+?)~~/g,
}
